### ISSUE TITLE
Ventana inutilizable tras crear nuevo control

### ISSUE THREAD

**Issue by juandiana** [genexuslabs/usercontrol-generator#10]
Luego de crear un nuevo control utilizando el diálogo 'Create User Control', se abre una nueva ventana del editor Atom con el directorio del nuevo proyecto de User Control creado.

El problema es que la ventana anterior permanece abierta y queda inutilizable ya que queda con la UI bloqueada y obliga al usuario a cerrarla.

**Comment by dmonza** [comment]
Queda pronto en la nueva versión
