### ISSUE TITLE
generar UC en depurar y release

### ISSUE THREAD

**Issue by ramunozp** [genexuslabs/usercontrol-generator#15]
cada vez que genero la versión debug o release tengo que repetir el proceso de 2 o mas veces hasta que crea la versión con todos los archivos, por que no lo hace a la primera.

**Comment by ramunozp** [comment]
ninguna respuesta?

**Comment by ggallotti** [comment]
@ramunozp Cuales son los archivos que no te copia en el primer Build debug? 
Podrías darnos un ejemplo?

Cualquier cosa que nos ayude a reproducir el problema más rápidamente es bienvenido.

**Comment by ramunozp** [comment]
lo natural es que mis UC tengan la siguiente estructura:
UC/
    css/
    js/
    fonts/
    img/
    properties.xml
    render.js
    render.xls
    uc.control
    img.gif
    icono.ico
    ... etc.

el probles que se produce es (a modo de ejemplo):
en un build deja fuera todas las carpetas
en otro build deja fuera en render.js
en otro build deja fuera algun contenido de las carpetas
*generalmente en un 4 build lo hace bien.*
nota: Esto funciona a la primera si borro a mano el contenido de la carpeta debug o release.

**Comment by ramunozp** [comment]
debo agregar que en MAC, hacer la versión Release provoca fallos con unas dependencias (librerias js) que no carga o no reconoce al renderizar.

**Comment by ramunozp** [comment]
alguna noticia?

**Comment by ramunozp** [comment]
Que sucede que no responden?

**Comment by ggallotti** [comment]
Hola Rodolfo,

El problema lo reproduje 1 vez, pero nunca más.

Le doy a Debug varias veces, pero siempre termina ok. 


Ví que había dependencias bastante viejas.
Así lo que hice fue actualizar a lo último y corregir algunas cosas.
La verdad que no sé si lo arreglará o no.

Te paso los archivos para que me digas como tu fue y en base a eso hacer el commit o no.

Pasos:
1. Descargar: https://www.dropbox.com/s/dhbz3pzy0brrr9r/myUsercontrol2.zip?dl=0
2. Extraer y reemplazar dichos archivos,  dentro del Proyecto de tu Usercontrol de Atom. 
3. Abrir una línea de comandos y ejecutar "npm install".  Si no tienes instalado NPM => https://www.npmjs.com/get-npm
4. Probar de nuevo a ver si con esto se da tu problema. 


Espero tus comentarios,

Saludos.

**Comment by ramunozp** [comment]
Estimado,

Solo remplace el js y json en el uc de ejemplo y funciono bien, no tengo que borrar mas los archivos en debug/Release, por lo menos. antes, para asegurarme que creara la nueva versión estaba obligado a borrar los archivo a a mano.

y el tema de los nombres?? (esto me complica, por que dejo el UC organizado por carpetas y estructura para agrupar todos mis UC y ademas comparten carpetas con js, css, etc.)



por ejemplo:



y un par de pregunta:

• qué comandos/funciones tengo disponible para usar en el archivo XSL?
• Hay algún tipo de opción para agregar licenciamiento en el desarrollo?


Atte
Rodolfo Muñoz

**Comment by ggallotti** [comment]
Solucionado en v.0.6.11
