### ISSUE TITLE
Nuevo UC

### ISSUE THREAD

**Issue by ramunozp** [genexuslabs/usercontrol-generator#16]
Al crear un nuevo uc, no renombre de forma correcta los nuevos archivos, es decir, el un llamado "my_usercontrol" genera lo siguiente:
- my_UsercontrolProperties.xml
- my_UsercontrolRender.js
- myUsercontrol.control
- myUsercontrolRender.xsl

Claramente, los nombres no siguen el mismo comportamiento. Por ahora tengo que renombrarlos manualmente.

**Comment by ggallotti** [comment]
Solucionado en v.0.6.11

**Comment by ggallotti** [comment]
Solucionado v.0.6.13
